name: Deploy to Apache

on:
  push:
    branches:
      - main  # or change to 'master' if needed

jobs:
  deploy:
    runs-on: self-hosted  # MUST be a self-hosted runner with Apache and permissions

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy files to Apache
        run: sudo cp -r * /var/www/html/
